services:
  kakalot_scraper:
    image: leadafk/kakalot_scraper
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../manga:/app/manga
      - ../to_scrape.conf:/app/to_scrape.conf
    healthcheck:
      test: ["CMD-SHELL", "/app/healthcheck.sh"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
